name: CosmeticWater
version: 1.0
main: me.espryth.cosmeticwater.CosmeticWaterPlugin
author: Espryth
api-version: 1.19
commands:
  cauldron:
    description: Gets a cauldron with a potion
    usage: /cauldron <potion>
